from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .menuViewSet import MenuViewSet
from .ingredientCreateView import IngredientCreateView
from .userFavoritesCreateView import UserFavoritesCreateView
from .userFavoritesDetailView import UserFavoritesDetailView