# Generated by Django 3.2.8 on 2021-10-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neverappApp', '0003_alter_ingredient_nameingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuhasingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='menuhasingredient',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredients',
            field=models.ManyToManyField(to='neverappApp.Ingredient'),
        ),
    ]
