# Generated by Django 3.2.8 on 2021-10-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neverappApp', '0004_auto_20211023_0131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuHasIngredient',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_menus',
            field=models.ManyToManyField(to='neverappApp.Menu'),
        ),
        migrations.DeleteModel(
            name='UsuarioHasMenu',
        ),
    ]
